### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/TenSEAL#17]
I ran the instructions in the README.md to install.

```
  103  [2020-04-09 22:02:08 +0100] git clone git@github.com:OpenMined/TenSEAL.git
  104  [2020-04-09 22:02:18 +0100] cd TenSEAL/
  108  [2020-04-09 22:03:13 +0100] git submodule init
  109  [2020-04-09 22:03:17 +0100] git submodule update
  110  [2020-04-09 22:03:31 +0100] pip install .
  111  [2020-04-09 22:04:59 +0100] history
```

and got the following error.

```
pip install .
Processing /Users/atrask/Dropbox/Laboratory/openmined/TenSEAL
Building wheels for collected packages: tenseal
  Building wheel for tenseal (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/atrask/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py'"'"'; __file__='"'"'/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-wheel-2mqw6869
       cwd: /private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/
  Complete output (48 lines):
  /Users/atrask/opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:453: UserWarning: Normalizing '0.1.2-dev' to '0.1.2.dev0'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  running build_ext
  Traceback (most recent call last):
    File "/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py", line 33, in run
      out = subprocess.check_output(['cmake', '--version'])
    File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 488, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
      restore_signals, start_new_session)
    File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py", line 93, in <module>
      zip_safe=False,
    File "/Users/atrask/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/atrask/opt/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py", line 36, in run
      ", ".join(e.name for e in self.extensions))
  RuntimeError: CMake must be installed to build the following extensions: _tenseal_cpp
  ----------------------------------------
  ERROR: Failed building wheel for tenseal
  Running setup.py clean for tenseal
Failed to build tenseal
Installing collected packages: tenseal
  Attempting uninstall: tenseal
    Found existing installation: tenseal 0.1.0.dev0
    Uninstalling tenseal-0.1.0.dev0:
      Successfully uninstalled tenseal-0.1.0.dev0
    Running setup.py install for tenseal ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/atrask/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py'"'"'; __file__='"'"'/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-record-uib43cop/install-record.txt --single-version-externally-managed --compile --install-headers /Users/atrask/opt/anaconda3/include/python3.7m/tenseal
         cwd: /private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/
    Complete output (57 lines):
    /Users/atrask/opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:453: UserWarning: Normalizing '0.1.2-dev' to '0.1.2.dev0'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/tenseal
    copying tenseal/version.py -> build/lib.macosx-10.9-x86_64-3.7/tenseal
    copying tenseal/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/tenseal
    creating build/lib.macosx-10.9-x86_64-3.7/tenseal/tensors
    copying tenseal/tensors/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/tenseal/tensors
    running build_ext
    Traceback (most recent call last):
      File "/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py", line 33, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/Users/atrask/opt/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py", line 93, in <module>
        zip_safe=False,
      File "/Users/atrask/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/atrask/opt/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/atrask/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py", line 36, in run
        ", ".join(e.name for e in self.extensions))
    RuntimeError: CMake must be installed to build the following extensions: _tenseal_cpp
    ----------------------------------------
  Rolling back uninstall of tenseal
  Moving to /Users/atrask/opt/anaconda3/lib/python3.7/site-packages/tenseal-0.1.0.dev0.dist-info/
   from /Users/atrask/opt/anaconda3/lib/python3.7/site-packages/~enseal-0.1.0.dev0.dist-info
  Moving to /Users/atrask/opt/anaconda3/lib/python3.7/site-packages/tenseal/
   from /Users/atrask/opt/anaconda3/lib/python3.7/site-packages/~enseal
ERROR: Command errored out with exit status 1: /Users/atrask/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py'"'"'; __file__='"'"'/private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-req-build-tjz7l9d0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/zc/t5ztbg0563q8r1f5b601mzzh00g5p3/T/pip-record-uib43cop/install-record.txt --single-version-externally-managed --compile --install-headers /Users/atrask/opt/anaconda3/include/python3.7m/tenseal Check the logs for full command output.
```

I'm on OSX Catalina, Python 3.7.6

**Comment by youben11** [comment]
@iamtrask  did you install CMake? seems like it couldn't find it.

**Comment by youben11** [comment]
You will also need to have Xcode installed.
