### ISSUE TITLE
encrypted1 and encrypted2 parameter mismatch

### ISSUE THREAD

**Issue by Propantheline** [OpenMined/TenSEAL#449]
## Description
The encrypted 5*64 matrix is multiplied with 64*784 plaintext matrix by the mm() function, and it reports ValueError: encrypted1 and encrypted2 parameter mismatch.

## Confusion
The encrypted matrix is multiplyable with np.random.rand(64,784), and mnist's data(64*784) will report an error, why is that?

**Comment by xuefeng-xu** [comment]
Hi @Propantheline, I came across similar error, here is my code
```python
import tenseal as ts

ctx = ts.context(ts.SCHEME_TYPE.CKKS,
                 poly_modulus_degree=8192,
                 coeff_mod_bit_sizes=[35,27,27,35])
ctx.global_scale = pow(2, 27)
ctx.generate_galois_keys()

x = [[0.1, 0.1], [0.1, 0.0]]
# x = [[0.1, 0.1], [0.1, 0.1]]

w = ts.ckks_tensor(ctx, [[0.1, 0.1], [0.1, 0.1]])
z = w.mm(x)
d = z.mm(x)
```
When ``x = [[0.1, 0.1], [0.1, 0.0]]``, I got the error below (no error when ``x = [[0.1, 0.1], [0.1, 0.1]]``)
```
Traceback (most recent call last):
  File "ten.py", line 14, in <module>
    d = z.mm(x)
  File "/Users/xxf/miniconda3/envs/ph/lib/python3.8/site-packages/tenseal/tensors/ckkstensor.py", line 118, in mm
    result = self.data.mm(other)
ValueError: encrypted1 and encrypted2 parameter mismatch
```
It seems that it's ``0.0`` cause this error since MNIST data also contains zeros.

**Comment by xuefeng-xu** [comment]
> Maybe you could check the shapes of x, w, and z, or you could increase the number of coefficients in coeff_mod_bit_sizes, which determines the number of homomorphic multiplications performed.

The shape of x, w, z are all (2,2). And I have try different ckks params, such as increase the number of coefficients, but I still got this error.

**Comment by xuefeng-xu** [comment]
> ## Description
> The encrypted 5_64 matrix is multiplied with 64_784 plaintext matrix by the mm() function, and it reports ValueError: encrypted1 and encrypted2 parameter mismatch.
> 
> ## Confusion
> The encrypted matrix is multiplyable with np.random.rand(64,784), and mnist's data(64*784) will report an error, why is that?

BTW, did you solve this error?

**Comment by Propantheline** [comment]
Sorry, I forgot how I did it then, and it didn't seem to fix it, I encrypted the plaintext matrix again and multiplied it with the ciphertext matrix to get no error. What I understand is to keep the ciphertext scale on a level, or the parameters don't match.

**Comment by xuefeng-xu** [comment]
> Sorry, I forgot how I did it then, and it didn't seem to fix it, I encrypted the plaintext matrix again and multiplied it with the ciphertext matrix to get no error. What I understand is to keep the ciphertext scale on a level, or the parameters don't match.

Thanks, it seems that TenSEAL does relin, rescale, and mod switch automatically. I still wonder why I got this error. Anyway, here is another script which receives a parameter mismatch error.
```python
import tenseal as ts

ctx = ts.context(ts.SCHEME_TYPE.CKKS,
                 poly_modulus_degree=32768,
                 coeff_mod_bit_sizes=[60,40,40,40,60])
ctx.global_scale = pow(2, 40)
ctx.generate_galois_keys()

x = [[0.1, 0.1], [0.1, 0.0]]
w = ts.ckks_tensor(ctx, [[0.1, 0.1], [0.1, 0.1]])
z = w.mm(x)

t = [[1., 0.], [0., 1.]]
# t = [[1., 0.0001], [0.0001, 1.]]
d = z * t
d.sum()
```
If ``t = [[1., 0.], [0., 1.]]``, I will get an error. But if ``t = [[1., 0.0001], [0.0001, 1.]]``, it's all good. The only difference is the first ``t`` contains ``0.``.
```
Traceback (most recent call last):
  File "tt.py", line 16, in <module>
    d.sum()
  File "/Users/xxf/miniconda3/envs/ph/lib/python3.8/site-packages/tenseal/tensors/abstract_tensor.py", line 153, in sum
    return self._wrap(self.data.sum(axis))
ValueError: encrypted1 and encrypted2 parameter mismatch
```

**Comment by xzfgtydxm** [comment]
Hello, did you solve this error?

**Comment by xuefeng-xu** [comment]
> Hello, did you solve this error?

No

**Comment by xzfgtydxm** [comment]
Thank you

**Comment by xzfgtydxm** [comment]
Now I use a function to ensure its decimal distance from 0 is sufficient, this parameter, after my testing, may be related to coeff_mod_bit_sizes.

```python
def adjust_weights_away_from_zero(weight_matrix, min_distance=1e-9):
    adjusted_matrix = weight_matrix.copy()
    near_zero_indices = np.abs(adjusted_matrix) < min_distance
    adjusted_matrix[near_zero_indices] = np.sign(adjusted_matrix[near_zero_indices]) * min_distance
    return adjusted_matrix
```
