### ISSUE TITLE
'tenseal._tenseal_cpp' Module Not Found

### ISSUE THREAD

**Issue by DRKorossy** [OpenMined/TenSEAL#498]
## Question
How do I fix a ModuleNotFoundError when trying to import tenseal?

## Further Information
In a nutshell, I'm getting a ModuleNotFoundError for 'tenseal._tenseal_cpp' and I don't know how to start working with the tenseal library.

To elaborate, find the program that I'm trying to run and the full error message below:

Programme: 
    - name: fhe.py
    - contents:
        import tenseal as ts
        print("hello, world")

[...path...]/venv/lib/python3.12/site-packages/tenseal/\_\_init\_\_.py", line 5, in <module>
    import _tenseal_cpp as _ts_cpp
ImportError: dlopen([...path...]/venv/lib/python3.12/site-packages/_tenseal_cpp.cpython-312-darwin.so, 0x0002): tried: '[...path...]/venv/lib/python3.12/site-packages/_tenseal_cpp.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/[...path...]/venv/lib/python3.12/site-packages/_tenseal_cpp.cpython-312-darwin.so' (no such file), '[...path...]/venv/lib/python3.12/site-packages/_tenseal_cpp.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...path...]/fhe.py", line 1, in <module>
    import tenseal as ts
  File "[...path...]/venv/lib/python3.12/site-packages/tenseal/\_\_init\_\_.py", line 7, in <module>
    import tenseal._tenseal_cpp as _ts_cpp
ModuleNotFoundError: No module named 'tenseal._tenseal_cpp'

## System Information
 - OS: iOS (13 inch MacBook Pro 2020)
 - CPU: 2 GHz Quad-Core Intel Core i5 (2020 model, before the M1 chips were introduced)
 - OS Version: Sonoma
 - Language Version: Python 3.12 
 - Package Manager Version: pip

## Additional Context
The error message mentions "have 'arm64', need 'x86_64h' or 'x86_64'". However, when checking using: uname -m
I get: x86_64. So I don't have arm64. My guess is that either the programme is unable to identify the x86_64 as it is, or there are missing files from the library. 

I'd appreciate any and all support, thanks.

**Comment by philomath213** [comment]
Release 0.3.16 should fix this issue.
@DRKorossy can you please try again and confirm that the issue is fixed?
